apply plugin: 'com.android.application'

android {
    compileSdk 34
    buildToolsVersion = "34.0.0"
    ndkVersion "25.1.8937393"

    defaultConfig {
        applicationId "com.tencent.ncnnyolov7"
        archivesBaseName = "$applicationId"

        minSdkVersion 24
        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    externalNativeBuild {
        cmake {
            version "3.22.1"
            path file('src/main/jni/CMakeLists.txt')
        }
    }

    dependencies {
        implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    }
    namespace 'com.tencent.ncnnyolov7'
    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
    }
}
